project:
  type: website

website:
  title: "Aishwarya's Visual Journey"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Introduction to R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Interactivity in R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"  
        - text: "Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Building Ternary Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"    
        - text: "Visualising Time-oriented Data"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Network Data Visualisation and Analysis"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
    - text: "In-Class Exercise"
      menu:
        - text: "Dotplot"
          href: "In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html"
        - text: "Interactivity"
          href: "In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html"
        - text: "Corrplot"
          href: "In-Class_Ex/In-Class_Ex05/In-Class_Ex05_Corrplot.html" 
        - text: "Ternary Plot"
          href: "In-Class_Ex/In-Class_Ex05/In-Class_Ex05_Ternary.html"    
        - text: "Heatmap"
          href: "In-Class_Ex/In-Class_Ex05/In-Class_Ex05_Heatmap.html" 
    - text: "Visualisation - Singapore"
      menu:
        - text: "Age-Population Pyramid - Singapore 2022 (Tableau)"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        - text: "Age-Population Pyramid - Singapore 2022 (RStudio)"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
        - text: "Is the Media Noise around Re-sale price (2022) right?"
          href: "Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html"
        - text: "Unpacking International Trade Relations with Singapore 2020-22"
          href: "Take-Home_Ex/Take-Home_Ex04/Take-Home_Ex04.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd 


format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

